site_name: My Docs
watch:
  - mkdocs.yml
  - docs/
  - src/
  - tests/

theme:
  name: material

plugins:
  - mkdocstrings:
      default_handler: R
      handlers:
        R:
          lib_loc: "~/myrepos/using-mkdocstrings-R/renv/library/linux-nixos-xantusia/R-4.5/x86_64-pc-linux-gnu"
